FROM node:18

WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .

EXPOSE 3001

CMD ["npm", "run", "start"]
# Use the below command instead for development with nodemon
# CMD ["npm", "run", "dev"]